# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imglink.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImglinkForm(object):
    def setupUi(self, ImglinkForm):
        ImglinkForm.setObjectName("ImglinkForm")
        ImglinkForm.resize(967, 688)
        self.pushButton = QtWidgets.QPushButton(ImglinkForm)
        self.pushButton.setGeometry(QtCore.QRect(570, 210, 89, 27))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(ImglinkForm)
        self.pushButton.clicked.connect(ImglinkForm.close)
        QtCore.QMetaObject.connectSlotsByName(ImglinkForm)

    def retranslateUi(self, ImglinkForm):
        _translate = QtCore.QCoreApplication.translate
        ImglinkForm.setWindowTitle(_translate("ImglinkForm", "Form"))
        self.pushButton.setText(_translate("ImglinkForm", "关闭"))
