# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'facerec.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FacerecForm(object):
    def setupUi(self, FacerecForm):
        FacerecForm.setObjectName("FacerecForm")
        FacerecForm.resize(967, 688)
        self.pushButton = QtWidgets.QPushButton(FacerecForm)
        self.pushButton.setGeometry(QtCore.QRect(570, 210, 89, 27))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(FacerecForm)
        self.pushButton.clicked.connect(FacerecForm.close)
        QtCore.QMetaObject.connectSlotsByName(FacerecForm)

    def retranslateUi(self, FacerecForm):
        _translate = QtCore.QCoreApplication.translate
        FacerecForm.setWindowTitle(_translate("FacerecForm", "Form"))
        self.pushButton.setText(_translate("FacerecForm", "关闭"))
