# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'facerec.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FacerecForm(object):
    def setupUi(self, FacerecForm):
        FacerecForm.setObjectName("FacerecForm")
        FacerecForm.resize(967, 688)

        FacerecForm.setMinimumSize(QtCore.QSize(967, 688))
        self.btn_stop = QtWidgets.QPushButton(FacerecForm)
        self.btn_stop.setGeometry(QtCore.QRect(690, 590, 90, 30))
        self.btn_stop.setObjectName("stop")
        self.btn_start = QtWidgets.QPushButton(FacerecForm)
        self.btn_start.setGeometry(QtCore.QRect(90, 590, 90, 30))
        self.btn_start.setObjectName("btn_start")
        self.label = QtWidgets.QLabel(FacerecForm)
        self.label.setGeometry(QtCore.QRect(120, 90, 640, 480))
        self.label.setStyleSheet("background-color:rgb(221, 255, 194);")
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.btn_close = QtWidgets.QPushButton(FacerecForm)
        self.btn_close.setGeometry(QtCore.QRect(690, 30, 90, 30))
        self.btn_close.setObjectName("btn_close")

        self.retranslateUi(FacerecForm)
        self.btn_close.clicked.connect(FacerecForm.close)
        QtCore.QMetaObject.connectSlotsByName(FacerecForm)

    def retranslateUi(self, FacerecForm):
        _translate = QtCore.QCoreApplication.translate
        FacerecForm.setWindowTitle(_translate("FacerecForm", "Form"))

        self.btn_stop.setText(_translate("FacerecForm", "停止"))
        self.btn_start.setText(_translate("FacerecForm", "开始"))
        self.label.setText(_translate("FacerecForm",
                                      "<html><head/><body><p><span style=\" font-style:italic;\">等待视频输入</span></p></body></html>"))
        self.btn_close.setText(_translate("FacerecForm", "关闭"))

