# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gesture.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GestureForm(object):
    def setupUi(self, GestureForm):
        GestureForm.setObjectName("GestureForm")
        GestureForm.resize(967, 688)
        self.pushButton = QtWidgets.QPushButton(GestureForm)
        self.pushButton.setGeometry(QtCore.QRect(570, 210, 89, 27))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(GestureForm)
        self.pushButton.clicked.connect(GestureForm.close)
        QtCore.QMetaObject.connectSlotsByName(GestureForm)

    def retranslateUi(self, GestureForm):
        _translate = QtCore.QCoreApplication.translate
        GestureForm.setWindowTitle(_translate("GestureForm", "Form"))
        self.pushButton.setText(_translate("GestureForm", "关闭"))
