# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'semantic.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SemanticForm(object):
    def setupUi(self, SemanticForm):
        SemanticForm.setObjectName("SemanticForm")
        SemanticForm.resize(967, 688)
        self.pushButton = QtWidgets.QPushButton(SemanticForm)
        self.pushButton.setGeometry(QtCore.QRect(380, 300, 89, 27))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(SemanticForm)
        self.pushButton.clicked.connect(SemanticForm.close)
        QtCore.QMetaObject.connectSlotsByName(SemanticForm)

    def retranslateUi(self, SemanticForm):
        _translate = QtCore.QCoreApplication.translate
        SemanticForm.setWindowTitle(_translate("SemanticForm", "Form"))
        self.pushButton.setText(_translate("SemanticForm", "关闭"))
