# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eyetrack.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EyetrackForm(object):
    def setupUi(self, EyetrackForm):
        EyetrackForm.setObjectName("EyetrackForm")
        EyetrackForm.resize(967, 688)
        self.pushButton = QtWidgets.QPushButton(EyetrackForm)
        self.pushButton.setGeometry(QtCore.QRect(570, 210, 89, 27))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(EyetrackForm)
        self.pushButton.clicked.connect(EyetrackForm.close)
        QtCore.QMetaObject.connectSlotsByName(EyetrackForm)

    def retranslateUi(self, EyetrackForm):
        _translate = QtCore.QCoreApplication.translate
        EyetrackForm.setWindowTitle(_translate("EyetrackForm", "Form"))
        self.pushButton.setText(_translate("EyetrackForm", "关闭"))
