# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eyetrack.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EyetrackForm(object):
    def setupUi(self, EyetrackForm):
        EyetrackForm.setObjectName("EyetrackForm")
        EyetrackForm.resize(967, 688)
        EyetrackForm.setMinimumSize(QtCore.QSize(967, 688))
        self.btn_show_cursor = QtWidgets.QPushButton(EyetrackForm)
        self.btn_show_cursor.setGeometry(QtCore.QRect(490, 590, 90, 30))
        self.btn_show_cursor.setObjectName("btn_show_cursor")
        self.btn_stop = QtWidgets.QPushButton(EyetrackForm)
        self.btn_stop.setGeometry(QtCore.QRect(690, 590, 90, 30))
        self.btn_stop.setObjectName("stop")
        self.btn_start = QtWidgets.QPushButton(EyetrackForm)
        self.btn_start.setGeometry(QtCore.QRect(90, 590, 90, 30))
        self.btn_start.setObjectName("btn_start")
        self.btn_remove_glass = QtWidgets.QPushButton(EyetrackForm)
        self.btn_remove_glass.setGeometry(QtCore.QRect(290, 590, 90, 30))
        self.btn_remove_glass.setObjectName("btn_remove_glass")
        self.label = QtWidgets.QLabel(EyetrackForm)
        self.label.setGeometry(QtCore.QRect(120, 90, 640, 480))
        self.label.setStyleSheet("background-color:rgb(221, 255, 194);")
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.btn_close = QtWidgets.QPushButton(EyetrackForm)
        self.btn_close.setGeometry(QtCore.QRect(690, 30, 90, 30))
        self.btn_close.setObjectName("btn_close")

        self.retranslateUi(EyetrackForm)
        self.btn_close.clicked.connect(EyetrackForm.close)
        QtCore.QMetaObject.connectSlotsByName(EyetrackForm)

    def retranslateUi(self, EyetrackForm):
        _translate = QtCore.QCoreApplication.translate
        EyetrackForm.setWindowTitle(_translate("EyetrackForm", "Form"))
        self.btn_show_cursor.setText(_translate("EyetrackForm", "显示注视点"))
        self.btn_stop.setText(_translate("EyetrackForm", "停止"))
        self.btn_start.setText(_translate("EyetrackForm", "开始"))
        self.btn_remove_glass.setText(_translate("EyetrackForm", "去除眼镜"))
        self.label.setText(_translate("EyetrackForm", "<html><head/><body><p><span style=\" font-style:italic;\">等待视频输入</span></p></body></html>"))
        self.btn_close.setText(_translate("EyetrackForm", "关闭"))