# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dehaze.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DehazeForm(object):
    def setupUi(self, DehazeForm):
        DehazeForm.setObjectName("DehazeForm")
        DehazeForm.resize(967, 688)
        self.pushButton = QtWidgets.QPushButton(DehazeForm)
        self.pushButton.setGeometry(QtCore.QRect(570, 210, 89, 27))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(DehazeForm)
        self.pushButton.clicked.connect(DehazeForm.close)
        QtCore.QMetaObject.connectSlotsByName(DehazeForm)

    def retranslateUi(self, DehazeForm):
        _translate = QtCore.QCoreApplication.translate
        DehazeForm.setWindowTitle(_translate("DehazeForm", "Form"))
        self.pushButton.setText(_translate("DehazeForm", "关闭"))
