# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'derain.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DerainForm(object):
    def setupUi(self, DerainForm):
        DerainForm.setObjectName("DerainForm")
        DerainForm.resize(905, 626)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DerainForm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.openfile_btn = QtWidgets.QPushButton(DerainForm)
        self.openfile_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.openfile_btn.setObjectName("openfile_btn")
        self.horizontalLayout_5.addWidget(self.openfile_btn)
        self.label = QtWidgets.QLabel(DerainForm)
        self.label.setMaximumSize(QtCore.QSize(80, 80))
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.process_label = QtWidgets.QLabel(DerainForm)
        self.process_label.setMaximumSize(QtCore.QSize(16777215, 80))
        self.process_label.setText("")
        self.process_label.setAlignment(QtCore.Qt.AlignCenter)
        self.process_label.setObjectName("process_label")
        self.horizontalLayout_5.addWidget(self.process_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(DerainForm)
        self.label_2.setMaximumSize(QtCore.QSize(120, 80))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.info_label = QtWidgets.QLabel(DerainForm)
        self.info_label.setMaximumSize(QtCore.QSize(16777215, 80))
        self.info_label.setText("")
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setObjectName("info_label")
        self.horizontalLayout_7.addWidget(self.info_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.video_compare_constrain = QtWidgets.QHBoxLayout()
        self.video_compare_constrain.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.video_compare_constrain.setObjectName("video_compare_constrain")
        self.verticalLayout.addLayout(self.video_compare_constrain)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(DerainForm)
        QtCore.QMetaObject.connectSlotsByName(DerainForm)

    def retranslateUi(self, DerainForm):
        _translate = QtCore.QCoreApplication.translate
        DerainForm.setWindowTitle(_translate("DerainForm", "Form"))
        self.openfile_btn.setText(_translate("DerainForm", "打开文件"))
        self.label.setText(_translate("DerainForm", "处理进度："))
        self.label_2.setText(_translate("DerainForm", "视频信息："))
